// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Domain.Models.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Candidates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateOnly(1999, 12, 12),
                            ContactNumber = "065498752",
                            Email = "marokom@gmail.com",
                            FullName = "Marko Markovic"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateOnly(2001, 6, 4),
                            ContactNumber = "068023654",
                            Email = "jovan@gmail.com",
                            FullName = "Jovan Jovanovic"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateOnly(2000, 8, 7),
                            ContactNumber = "3265410",
                            Email = "smithana@gmail.com",
                            FullName = "Ana Smith"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateOnly(1994, 6, 5),
                            ContactNumber = "852741036",
                            Email = "kate@gmail.com",
                            FullName = "Kate Brown"
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateOnly(1998, 1, 1),
                            ContactNumber = "06452310",
                            Email = "mmarija@gmail.com",
                            FullName = "Marija Matic"
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateOnly(2000, 10, 9),
                            ContactNumber = "9872015",
                            Email = "paul123@gmail.com",
                            FullName = "Paul Blue"
                        });
                });

            modelBuilder.Entity("Domain.Models.CandidateSkill", b =>
                {
                    b.Property<int>("CandidateId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("CandidateId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("CandidatesSkill");

                    b.HasData(
                        new
                        {
                            CandidateId = 1,
                            SkillId = 1
                        },
                        new
                        {
                            CandidateId = 1,
                            SkillId = 2
                        },
                        new
                        {
                            CandidateId = 2,
                            SkillId = 2
                        },
                        new
                        {
                            CandidateId = 5,
                            SkillId = 7
                        },
                        new
                        {
                            CandidateId = 4,
                            SkillId = 6
                        });
                });

            modelBuilder.Entity("Domain.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "C#"
                        },
                        new
                        {
                            Id = 2,
                            Name = "React"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Java"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Python"
                        },
                        new
                        {
                            Id = 5,
                            Name = "English"
                        },
                        new
                        {
                            Id = 6,
                            Name = "German"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Spanish"
                        });
                });

            modelBuilder.Entity("Domain.Models.CandidateSkill", b =>
                {
                    b.HasOne("Domain.Models.Candidate", "Candidate")
                        .WithMany("Skills")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Skill", "Skill")
                        .WithMany("CandidateSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Domain.Models.Candidate", b =>
                {
                    b.Navigation("Skills");
                });

            modelBuilder.Entity("Domain.Models.Skill", b =>
                {
                    b.Navigation("CandidateSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
